---
title: "Apply Scores to Forecasts"
format: html
editor: visual
---

```{r message = FALSE}
knitr::opts_chunk$set(message=FALSE, warning = FALSE)
suppressPackageStartupMessages(source("packages.R"))
for (f in list.files(here::here("R"), full.names = TRUE)) source (f)
```

## Lets apply scoring rules to all of the Forecasts

```{r}
library(minioclient)
library(stringr)
install_mc()

fire_box <- fire_bbox(fire = "august_complex", pad_box = TRUE)

# Ingest data ------------------------------------------------------------
gdalcubes::gdalcubes_options(parallel=TRUE)

# use ingest_planetary_data function to extract raster cube for fire bounding box between Jan 1 2002 and July 1 2023.
raster_cube <- ingest_planetary_data(start_date = "2019-01-01", 
                                     end_date = "2023-07-01", 
                                     box = fire_box$bbox,
                                     srs = "EPSG:4326",
                                     dx = 0.1, 
                                     dy = 0.1, 
                                     dt = "P30D",
                                     collection = "modis-15A2H-061",
                                     asset_name = "Lai_500m")

# create target file
date <- '2023-06-01'

target <- create_target_file(cuberast = raster_cube,
                             date = date,
                             dir = "/vsis3/spat4cast-targets",
                             mask = fire_box$maskLayer)

# target <- "lai_recovery-target-2023-05-10.tif"


mc_alias_set("efi", "data.ecoforecast.org",
             Sys.getenv("AWS_ACCESS_KEY_ID"), Sys.getenv("AWS_SECRET_ACCESS_KEY"))

submitted <- mc_ls("efi/spat4cast-submissions/variable=lai_recovery/site_id=august_complex/", recursive = TRUE)

scored <- mc_ls("efi/spat4cast-scores/variable=lai_recovery/site_id=august_complex/", recursive = TRUE)

submitted <- unique(str_extract(submitted, ".*/reference_date=.*(?=/)"))

scored <- unique(str_extract(scored, ".*/reference_date=.*(?=/)"))

subs_to_score <- submitted[which(submitted %in% scored == 0)]

subs_to_score <- paste0("efi/spat4cast-submissions/variable=lai_recovery/site_id=august_complex/",subs_to_score,"/")

if(length(subs_to_score) > 0){
  for(i in subs_to_score){
    model_id <- str_extract(i, "(?<=model_id=).*(?=/reference_date=)")
    ref_date <- str_extract(i, "(?<=reference_date=).*(?=/)" )
    #dir <- str_sub(i, 1L, end = -2L)
    dir.create("files")
    mc_cp(i, "files", recursive = TRUE)
  
    file_names <- mc_ls(i)
    parametric_ind <- if_else(1 %in% str_detect(file_names, c("lognormal|normal|bernoulli|beta|uniform|gamma|logistic|exponential|poisson")) == TRUE, 1, 0)
    if(parametric_ind == 1){
      score_dir <- scoring_spat_parametric("files", target, "score_dir")
      spat4cast_score_submit(score_dir, model_id, reference_date = ref_date)
    }else{
      score_dir <- scoring_spat_ensemble("files", target, "score_dir")
      spat4cast_score_submit(score_dir, model_id, reference_date = ref_date)
    }
  }
}else{}

```

## Lets Get visualizations of each of the scored forecasts

```{r}
scored <- mc_ls("efi/spat4cast-scores/variable=lai_recovery/site_id=august_complex/", recursive = TRUE)

scored <- unique(str_extract(scored, ".*/reference_date=.*(?=/)"))

for (i in scored){
  model_id <- str_extract(i, "(?<=model_id=).*(?=/reference_date=)")
  ref_date <- str_extract(i, "(?<=reference_date=).*(?=/)" )
  #dir <- str_sub(i, 1L, end = -2L)
  dir.create("files")
  mc_cp(i, "files", recursive = TRUE)
  file_names <- mc_ls(i)
   
  for( j in file_names){
    if(str_detect(j, "crps") == TRUE){
      temp_rast <- rast(paste0("files/",j))
      plot(temp_rast, main = paste0("CRPS Score for", model_id,"-",ref_date))
    }else{
      temp_rast <- rast(paste0("files/",j))
      plot(temp_rast, main = paste0("LOG Score for", model_id,"-",ref_date))
    }
  }
}


A <- c("A", "B", "C")
B <- c("A", "B", "C")

a <- A[which(A %in% B == 0)]



```
