---
title: "EFI_2025_Workshop"
author: "John Smith, Will Hammond, Chris Jones, David Durden"
date: "2025-04-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# 1 About this tutorial

## 1.1 Learning objectives

-   Overview of the [Post Fire Recovery - MODIS LAI](https://projects.ecoforecast.org/neon4cast-docs/)#to do replace with actual forecast link
    theme for the [NEON Ecological Forecast
    Challenge](https://projects.ecoforecast.org/neon4cast-ci/)
-   How to download the necessary data from Planentary Computer
-   How to create a simple forecast for the Post Fire Recovery theme
-   How to submit/score a forecast to evaluate its accuracy


## 1.2 Target user groups for this tutorial

This tutorial is intended to be used by ecological forecasters at any
stage of expertise and may be used as a learning tool as an introduction
to forecasting properties of ecological processes spatially and temporally.
Below, we provide code for introductory examples to walk through the
entire process of creating and submitting a forecast to the Ecological 
Forecasting challenge. This includes:

1.  Accessing target datasets of MODIS LAI.
2.  Accessing climate forecast data to use as drivers in models
    predicting LAI recovery post fire.
3.  How to create models for raster data.
4.  How to submit a forecast to the forecast challenge

Upon completing this tutorial, participants should be able to create and
submit forecasts to the MODIS LAI Post Fire Recovery theme of the EFI RCN NEON
Ecological Forecasting challenge.

## 1.3 Things you will need to complete this tutorial

You will need a current version of R (v4.2 or newer) to complete this
tutorial. We also recommend the RStudio IDE to work with R.

To complete the workshop via this markdown document the following
packages will need to be installed:

-   `tidyverse`
-   `lubridate`
-   `tsibble`
-   `stars`
-   `gdalcubes`
-   `rstac`
-   `terra`
-   `scoringRules`
-   `forecast`
-   `nimble`
-   `spatstat.sparse`
-   `assertthat`
-   `minioclient`
-   `purrr`
-   `remotes` (to install neon4cast from gitHub)
-   `neon4cast` (from github)

The following code chunk should be run to install packages.

``` r
install.packages('tidyverse') # collection of R packages for data manipulation, analysis, and visualisation
install.packages('lubridate') # working with dates and times
install.packages('tsibble') # working with timeseries data
install.packages('fable') # running forecasts
install.packages('fabletools') # helper functions for using fable
install.packages('remotes')
install.packages('tsibble') # package for dealing with time series data sets and tsibble objects
remotes::install_github('eco4cast/neon4cast') # package from NEON4cast challenge organisers to assist with forecast building and submission
remotes::install_github("eco4cast/score4cast") # package to score forecasts
```

Then load the packages.

``` r
version$version.string
```

    ## [1] "R version 4.3.1 (2023-06-16 ucrt)"

``` r
library(tidyverse)
library(lubridate)
library(tsibble)
library(fable)
library(fabletools)
library(neon4cast)
library(score4cast)
```

# 2 Introduction

## 2.1 [The NEON Ecological Forecast Challenge](https://projects.ecoforecast.org/neon4cast-ci/)

The Challenge has been organized by the Ecological Forecasting
Initiative Research Coordination Network ([EFI
RCN](https://ecoforecast.org/)).

The Challenge asks the scientific community to produce ecological
forecasts of future observations of ecological data that will be
collected and published by the [National Ecological Observatory Network
(NEON)](https://www.neonscience.org/). The Challenge is split into [five
themes](https://projects.ecoforecast.org/neon4cast-ci/targets.html#sec-starting-sites)
that span aquatic and terrestrial systems, and population, community,
and ecosystem processes across a broad range of ecoregions. We are
excited to use this Challenge to learn more about the predictability of
ecological processes by forecasting NEON data before it is collected.

Which modeling frameworks, mechanistic processes, and statistical
approaches best capture community, population, and ecosystem dynamics?
These questions are answerable by a community generating a diverse array
of forecasts. The Challenge is open to any individual or team from
anywhere around the world that wants to submit forecasts. Learn more
about how you can participate
[here.](https://projects.ecoforecast.org/neon4cast-ci/instructions.html).

## 2.2 Goals for forecasts of post fire recovery



## 2.3 Overview of the [MODIS LAI Post Fire Recovery](https://projects.ecoforecast.org/neon4cast-docs/) theme

**What**: Forecast abundance and/or richness of ground beetles
(carabids) collected in pitfall traps, standardized to sampling effort
(trap night). More information about the NEON data product
(DP1.10022.001, Ground beetles sampled from pitfall traps) we are
forecasting can be found
[here](https://data.neonscience.org/data-products/DP1.10022.001). Note
that we are not downloading the target dataset from the NEON data
portal. Rather, we will download a version of the dataset that has been
simplified and preformatted for this challenge by the EFI RCN.
Specifically, the targets are:

-   `abundance`: Total number of carabid individuals per trap-night,
    estimated each week of the year at each NEON site
-   `richness`: Total number of unique ‘species’ in a sampling bout for
    each NEON site each week.

**Where**: 3 Fires  [Fire Database](https://www.neonscience.org/field-sites/explore-field-sites).


```


**When**: 

# 3 Forecasting MODIS LAI Recovery Post Fire

## 3.1 Define spatial and temporal parameters for our forecast


## 3.2 Read in the data


## 3.3 Visualise the target data


## 3.4 Create the training dataset



## 3.5 Example forecasts: some simple models



### 3.5.1 Forecast MODIS LAI post fire: random walk model



### 3.5.2 Forecast MODIS LAI post fire: gridded ARIMA model


```

Does this forecast seem reasonable?

## 3.6 How to submit a forecast to the NEON Forecast Challenge


```

# 4 Evaluating your forecast

## 4.1 How your submission will be scored



## 4.2 How to score your own forecast

-   Which model(s) did best?
-   What might explain the differences in scores between the different
    models?

# 5 What’s next?

-   The forecasts we created here were relatively simple. What are ideas
    you have to improve the forecasts?
-   How could you expand on this forecasting exercise? More fires?
    Different forecast horizons?
-   How could you apply what you have learned here in your research or
    teaching?

# 6 Acknowledgements

